apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-intelligent-investor-backend-prep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-intelligent-investor-backend-prep
  template:
    metadata:
      labels:
        app: the-intelligent-investor-backend-prep
    spec:
      containers:
        - name: the-intelligent-investor-backend
          image: quay.io/roni-tamari/the-intelligent-investor-backend:prep
          ports:
            - containerPort: 4000
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
              name: postgres-secret
              key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: the-intelligent-investor-backend-prep
spec:
  selector:
    app: the-intelligent-investor-backend-prep
  ports:
    - name: http
      port: 4000
      targetPort: 4000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: the-intelligent-investor-backend-prep
spec:
  to:
    kind: Service
    name: the-intelligent-investor-backend-prep
  port:
    targetPort: http
  tls:
    termination: edge